### ISSUE TITLE
Extractor Module doesn't work 

### ISSUE THREAD

**Issue by XHang** [RS485/LogisticsPipes#1649]
When the module is installed at the beginning, it still works normally, but after a period of time has passed, it no longer picks up items. I have to take the module off and put it back in before it can work again.

use mod version:0.10.3.114
use Minecraft version:1.12.2

**Comment by skylvsme** [comment]
Worked with the same versions. At first, I connected a multiple chassis pipes to furnaces and put the extractor module in it.

At first, when I put some ore to furnace, extractor module worked properly, but when furnace become empty and I try to have to extractor module be working, there's no extracted items by it.

UPD: seems to be not fixed in 0.10.4.5

**Comment by MaksimHawkins** [comment]
It seems to be working in 0.10.4.5 (marked as Alpha in CursedForge, but i will use it instead)

**Comment by bziemons** [comment]
Needs to be retested in [0.10.4.49](https://ci.rs485.network/job/LogisticsPipes-0.10.4/49/artifact/build/libs/logisticspipes-0.10.4.49.jar).

**Comment by Celestial0579** [comment]
I have the same issue and tested it in the latest version of the tekkit 2 modpack (Minecraft 1.12.2). I changed to the logistics pipes version 0.10.4.49 and it still doesnt work. If you need further information, pls tell me
![2024-01-28_15 08 48](https://github.com/RS485/LogisticsPipes/assets/113726264/5383c9ae-c467-4a53-8f7e-ffcc10fbf359)
![2024-01-28_15 08 20](https://github.com/RS485/LogisticsPipes/assets/113726264/dd3a1df3-a796-4562-b23e-dc38f5aac638)
![2024-01-28_15 06 54](https://github.c
![2024-01-28_15 06 51](https://github.com/RS485/LogisticsPipes/assets/113726264/a0b9f00b-f056-468e-bbbe-6788789c1508)
om/RS485/LogisticsPipes/assets/113726264/51ebfafb-2927-42fe-9eba-89ceda0b8807)

**Comment by bziemons** [comment]
Let's close the older issues and track that one in #1704
